### PR TITLE
Patch legal? regexp vulnerability

### PR DESCRIPTION
**Pull request by tilsammans**
See http://sakurity.com/blog/2015/06/04/mongo_ruby_regexp.html

### CODE REVIEW

**Comment by tagrudev** [comment]
+1

**Comment by aganov** [comment]
I think /Z should be /z

>\z Matches the end of the string.
> \Z Matches the end of the string unless the string ends with a "\n" (\Z allows new line)

**Comment by durran** [comment]
Thanks, but this is fixed in master already.

**Comment by elhu** [comment]
Actually, the problem is still present for the 2.x versions of the gem. Is there any plans to backport it?
Unless I'm mistaken, we're stuck with ``bson`` 2.x because of the dependency specification in ``moped`` (``bson ~> 2.2``)...

**Comment by durran** [comment]
@elhu I've just released a new version of Moped that updates the dependency to minimum bson 3.0.4.

**Comment by Davidslv** [comment]
Seems you ignored @aganov comment

**Comment by durran** [comment]
I didn't - the pull request is incorrect, the commit I pushed uses `\z`.

**Comment by Davidslv** [comment]
:+1:

**Comment by elhu** [comment]
Great, thank you very much @durran !

**Pull request closed without merging**
