### PR TITLE
Renamed extension from native to bson_native

### PR DESCRIPTION
**Pull request by genki**
Current extension name "native" is too loud in global namespace.
So I propose to add prefix "bson_" and change it to "bson_native".

### CODE REVIEW

**Comment by estolfo** [comment]
Hi @genki 
What do you mean by "too loud"?
It's implied that it's the native bson extension, as the gem name is bson. Let me know why exactly you'd like a repetition of the gem name in the native file name.

**Comment by genki** [comment]
I meant, we can `require "native"` anywhare. Isn't it annoying?

**Comment by durran** [comment]
I have no problem changing the name - it doesn't break the public API. If we do, we should also change the java extensions as well, i.e. `NativeService` should probably become `BSONNativeService`.

**Comment by genki** [comment]
@durran I think It's not necessary because the Java extension already has prefix `bson-`. I just tried to bring its manner to Ruby :)

**Pull request merged**
