### PR TITLE
RUBY-2066 Extended json serialization


### PR DESCRIPTION
**Pull request by p-mongo**

### CODE REVIEW

**Comment by p-mongo** [comment]
https://jira.mongodb.org/browse/RUBY-2066

**Comment by ixti** [comment]
This PR breaks cases when Time has nanoseconds:

``` ruby
Time.utc(2020, 02, 02, 23, 59, 59, 999_999)
```

Due to `#to_f` not able to correctly represent nanoseconds (which is written in Ruby documentation):

> Note that IEEE 754 double is not accurate enough to represent the exact number of nanoseconds since the Epoch.
> -- https://ruby-doc.org/core-2.6.3/Time.html#method-i-to_f

That means, all Rails apps using `{ $lte: time.end_of_* }` are doomed to get absolutely wrong result, time will be serialized as beginning of next day.

**Comment by p-mongo** [comment]
@ixti Thank you for the report. Can you please create an issue at https://jira.mongodb.org/browse/RUBY which includes a snippet reproducing the problem, the expected result and the actual result?

**Comment by ixti** [comment]
@p-mongo Sure, I'm trying to prepare a good example.

**Comment by ixti** [comment]
https://jira.mongodb.org/browse/RUBY-2145

**Pull request merged**
