### PR TITLE
RUBY-1164 Add #to_bson and #as_json directly on Regexp::Raw to handle roundtripping options

### PR DESCRIPTION
**Pull request by estolfo**
- Allow Regexp::Raw to be serialized directly, without instantiating a Ruby Regexp so that options can be roundtripped.
- Allow #to_json to be called on a Regexp::Raw object directly so that options are preserved when providing the extended json representation.
- Always add the 'm' option when serializing a Ruby Regexp object, as Ruby always has the BSON equivalent of 'm' on.
- Only add the 's' option if the Ruby Regexp object has the 'm' option, as this corresponds to the BSON 's' option. See http://www.regular-expressions.info/modifiers.html
- Keep previous API where options can be provided as an Integer to Regexp::Raw and are serialized as they were before. Will be deprecated in next major version (5.0)

### CODE REVIEW

**Comment by mzikherman** [comment]
Hi! Sorry for commenting on this PR, I didn't see an `Issues` tab on this repo and wasn't sure the best way.

I suspect that this commit: https://github.com/mongodb/bson-ruby/pull/71/commits/d42c6ec9e07e252699f000f4dfaa54043e8572e3 (in this PR), creates a performance issues on prefixed regular expression queries.

It's my understanding that prefixed expressions: `/^something/`, should be able to efficiently use an index on that field (vs non-anchored `/something/`). However, it seems like `/^something/m` no longer lets Mongo use the index efficiently (which makes sense to me, the benefit from prefixing is being lost by requiring a full scan of each string for newlines).

I noticed the performance hit coming from a [slugging library for Mongoid](https://github.com/mongoid/mongoid-slug), and I described it further with some `explain()` output in https://github.com/mongoid/mongoid-slug/issues/235.

My question: is this a regression/performance issue that should be addressed in this repo? Might a fix be a way to specify a regular expression w/o this option (currently it looks like this option will always be added and can't be turned off)?

I'm not 100% sure of the next step re: proposing/implementing a fix but I am happy to try if pointed in the right direction!

Thanks for considering.

**Comment by estolfo** [comment]
Hi @mzikherman 

These code changes were introduced to account for the fact that Ruby regular expressions always have BSON regular expression's equivalent of 'm' on. That means, whenever a Ruby regular expression is serialized, the 'm' option must be added.

There is a class provided by the bson gem, `Regexp::Raw`, to allow Ruby users to get around this. You can simply create a regular expression like this:

```ruby
Regexp::Raw.new("^something")
```

This code example will show you the difference between serializing a Ruby regexp versus a Regexp::Raw object:

```ruby
2.2.0 :002 > regexp_ruby = /^b403158/
 => /^b403158/ 
2.2.0 :003 > regexp_ruby.to_bson
 => #<BSON::ByteBuffer:0x007fcf20ab8028> 
2.2.0 :004 > _.to_s
 => "^b403158\x00m\x00" 
2.2.0 :005 > regexp_raw = Regexp::Raw.new("^b403158")
 => #<BSON::Regexp::Raw:0x007fcf21808f98 @pattern="^b403158", @options=""> 
2.2.0 :006 >  regexp_raw.to_bson
 => #<BSON::ByteBuffer:0x007fcf213622f0> 
2.2.0 :007 > _.to_s
 => "^b403158\x00\x00" 
```

So please use the `Regexp::Raw` class to instantiate your BSON regular expressions to get the exact pattern and options you want.
Does that make sense? Let me know if you have anymore questions!
And for future reference, you're welcome to open a ticket in our Jira project for Ruby: https://jira.mongodb.org/browse/RUBY

Emily

**Comment by mzikherman** [comment]
Thanks for the quick reply!

Yep, everything you said makes perfect sense to me, it seems like the direct fix for this issue is to just use the provided `Regexp::Raw` class then, which I'll happily PR to the [slugging gem](https://github.com/mongoid/mongoid-slug).

I may reply here if I have any other questions for this since we already have the thread going, but thank you for the Jira link! Will definitely give it a look through and put any new issues there.

Matt

**Comment by estolfo** [comment]
Great, I'm glad that makes sense. I've actually opened [a ticket](https://jira.mongodb.org/browse/RUBY-1197) so that other users searching our RUBY project for this subject will find the explanation. Feel free to continue commenting there. Thanks!

**Comment by mzikherman** [comment]
Hi!

So, after getting sidetracked for a while I've come back to this in order to update the [slug gem](https://github.com/mongoid/mongoid-slug) to use `Regexp::Raw` so as to facilitate being able to update mongo versions, etc. w/o running into the perf issue we'd get with the implicit 'multiline' options.

Everything is fine except for a couple of failing specs around slug generation of embedded documents. Digging a bit further, I think I've found a few simple examples of queries that yield different results when using `Regexp::Raw` versus Ruby's native `Regexp`. I'm not 100% sure where to log or investigate the issues further (I suspect [Mongoid](https://github.com/mongodb/mongoid)).

### Repro

Consider two simple models, one embedded in the other:

``` ruby
class Book
  include Mongoid::Document
  include Mongoid::Slug
  field :title

  slug :title, history: true, max_length: nil
  embeds_many :subjects
end

class Subject
  include Mongoid::Document
  include Mongoid::Slug
  field :name
  slug :name, scope: :book, history: true
  embedded_in :book
end
```

There is one record of each:

``` ruby
pp Book.first.as_document; nil
D, [2017-03-27T17:32:55.224311 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | STARTED | {"find"=>"books", "filter"=>{}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
D, [2017-03-27T17:32:55.224891 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | SUCCEEDED | 0.000489s
{"_id"=>BSON::ObjectId('58d97a7eb1b92212a30909bf'),
 "_type"=>"Book",
 "title"=>"A Thousand Plateaus",
 "_slugs"=>["a-thousand-plateaus"],
 "subjects"=>
  [{"_id"=>BSON::ObjectId('58d97b20b1b92212a30909c0'),
    "name"=>"Psychoanalysis",
    "_slugs"=>["psychoanalysis"]}]}
```

We have the following set of queries:

``` ruby
Book.where(:"subjects.name" => /^Psycho/)
=> #<Mongoid::Criteria
  selector: {"subjects.name"=>/^Psycho/}
  options:  {}
  class:    Book
  embedded: false>

Book.where(:"subjects.name" => Regexp::Raw.new("^Psycho"))
=> #<Mongoid::Criteria
  selector: {"subjects.name"=>#<BSON::Regexp::Raw:0x007ff986969970 @pattern="^Psycho", @options="">}
  options:  {}
  class:    Book
  embedded: false>
```

and the counts of both:

```ruby
Book.where(:"subjects.name" => /^Psycho/).count
D, [2017-03-27T17:29:22.186242 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.count | STARTED | {"count"=>"books", "query"=>{"subjects.name"=>/^Psycho/}}
D, [2017-03-27T17:29:22.190440 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.count | SUCCEEDED | 0.0015589999999999998s
=> 1

Book.where(:"subjects.name" => Regexp::Raw.new("^Psycho")).count
D, [2017-03-27T17:31:47.034269 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.count | STARTED | {"count"=>"books", "query"=>{"subjects.name"=>#<BSON::Regexp::Raw:0x007ff9869236f0 @pattern="^Psycho", @options="">}}
D, [2017-03-27T17:31:47.035141 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.count | SUCCEEDED | 0.0007599999999999999s
=> 1
```

Both work as expected.

Now, constructing the query in this style:

``` ruby
Book.first.subjects.where(name: /^Psycho/)
D, [2017-03-27T17:33:41.682478 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | STARTED | {"find"=>"books", "filter"=>{}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
D, [2017-03-27T17:33:41.683182 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | SUCCEEDED | 0.000603s
=> #<Mongoid::Criteria
  selector: {"name"=>/^Psycho/}
  options:  {}
  class:    Subject
  embedded: true>

Book.first.subjects.where(name: Regexp::Raw.new("^Psycho"))
D, [2017-03-27T17:34:07.780532 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | STARTED | {"find"=>"books", "filter"=>{}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
D, [2017-03-27T17:34:07.781343 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | SUCCEEDED | 0.000691s
=> #<Mongoid::Criteria
  selector: {"name"=>#<BSON::Regexp::Raw:0x007ff98685ac78 @pattern="^Psycho", @options="">}
  options:  {}
  class:    Subject
  embedded: true>
```

So far, everything seems fine.

But wait! The counts don't match, and the last version of this query doesn't work.

``` ruby
Book.first.subjects.where(name: /^Psycho/).count
D, [2017-03-27T17:34:40.052729 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | STARTED | {"find"=>"books", "filter"=>{}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
D, [2017-03-27T17:34:40.053964 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | SUCCEEDED | 0.000518s
=> 1

Book.first.subjects.where(name: Regexp::Raw.new("^Psycho")).count
D, [2017-03-27T17:34:47.020777 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | STARTED | {"find"=>"books", "filter"=>{}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
D, [2017-03-27T17:34:47.021418 #4771] DEBUG -- : MONGODB | localhost:27017 | mongoid_slug_test.find | SUCCEEDED | 0.000716s
=> 0
```

This seems to be a difference in the way `.where` is evaluated for embedded (in-memory) objects. You can see from the log output that there is nothing that hits the database after the initial book is loaded.

I was unsuccessful in determining where in [Mongoid](https://github.com/mongodb/mongoid) this might be happening, though I suspect that's where an issue might lie.

Would you be able to advise or point me to where I can investigate this further? I was stymied by not being able to do `.method(:where)` successfully.

``` ruby
Book.first.subjects.method(:where)
NameError: undefined method `where' for class `Array'
```

Thanks for all the help so far!

**Comment by estolfo** [comment]
Hi @mzikherman !

Thanks for the thorough explanation. The reason the BSON::Regexp::Raw object is made available by the bson gem is to account for the fact that the ruby native regexp type doesn't have the same behavior as the regexp on the server. With the BSON::Regexp::Raw object, a user can be explicit about the pattern and options of the regular expression being serialized. That said, it doesn't make sense, in theory, to use this object to query documents in memory; you aren't sending this query to the server, so you can use the native Ruby regular expression type.

With the way the in-memory matching currently works in Mongoid, you won't get any matches if you use the BSON::Regexp::Raw type, because Mongoid doesn't know how to handle the object. Nevertheless, I've just updated a pull request against Mongoid that allows you to use a BSON::Regexp::Raw object for an in-memory query selector. Ultimatel,y you end up using a native regular expression to do the search anyway, so you'll find that it'll have the same behavior if you pass a native regexp or the bson raw one.

Let me know if you get a chance to try it out. Here is your example using the PR changes:

```ruby
> b = Book.first
D, [2017-03-29T13:52:56.805527 #61940] DEBUG -- : MONGODB | localhost:27017 | mongoid_test.find | STARTED | {"find"=>"books", "filter"=>{}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
D, [2017-03-29T13:52:56.806128 #61940] DEBUG -- : MONGODB | localhost:27017 | mongoid_test.find | SUCCEEDED | 0.000509s
=> #<Book _id: 58dba011f1286ef1f4b40ace, title: "A Thousand Plateaus">
> b.subjects.where(name: /^Psycho/).count 
=> 1
> b.subjects.where(name: BSON::Regexp::Raw.new("^Psycho")).count
=> 1
```

Note that you have to be explicit about the namespace of the BSON::Regexp::Raw object, as there is module in Mongoid for extra instance and class methods on Regexp.

Let me know if you have any questions!
Emily

**Comment by mzikherman** [comment]
Thanks so much for the help and response (and PR)! I went ahead and used your suggestion (falling back to Ruby's `Regexp` for the in-memory case) and for a [pull request](https://github.com/mongoid/mongoid-slug/pull/238) to the slug gem.

I'll check out the your PR locally and see how that looks, thanks again!

**Comment by estolfo** [comment]
Great, I just looked at the PR you've opened against mongoid-slug and it looks good to me. With the PR I've opened against Mongoid, you could get rid of the embedded? check [here](https://github.com/mongoid/mongoid-slug/pull/238/files#diff-96c3b0a4d8c9b307ad0af586d4de9886R130), but for backwards compatibility, you should probably leave that logic. You might also run into namespace issues if you don't write [this line](https://github.com/mongoid/mongoid-slug/pull/238/files#diff-96c3b0a4d8c9b307ad0af586d4de9886R133) as ``BSON::Regexp::Raw.new(escaped_pattern)``
Thanks again!
Emily

**Pull request merged**
